# Generated by Django 2.1.5 on 2019-01-11 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.BigIntegerField()),
                ('password', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=50)),
                ('bus_no', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.PositiveSmallIntegerField()),
                ('enter_device_id', models.CharField(max_length=20)),
                ('exit_device_id', models.CharField(max_length=20)),
                ('balance', models.PositiveSmallIntegerField()),
                ('owner', models.CharField(max_length=20)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
        ),
    ]
