# Generated by Django 2.1.5 on 2019-01-11 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateField()),
                ('created_date', models.DateField()),
                ('Balance', models.PositiveIntegerField()),
                ('card_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=20)),
                ('end', models.CharField(max_length=20)),
                ('fare', models.PositiveSmallIntegerField()),
                ('distance', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('device_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.BigIntegerField()),
                ('address', models.CharField(max_length=50)),
                ('card_key', models.BigIntegerField()),
                ('blood_group', models.CharField(max_length=3)),
                ('user_type', models.CharField(max_length=20)),
                ('register_date', models.DateField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='card_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='card',
            name='card_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
