# Generated by Django 2.1.5 on 2019-01-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card_key',
            field=models.CharField(max_length=16),
        ),
    ]
